FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    streamlit \
    pandas \
    joblib \
    pyarrow \
    psycopg2-binary \
    scikit-learn \
    scipy \
    protobuf \
    xgboost 
EXPOSE 8501

# CMD ["streamlit", "run", "app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]